### PR TITLE
Loading error

### PR DESCRIPTION
**Pull request by Forrestdarabian**
# Description

Added Progress/Loading Animations to Buttons

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
clean code

**Review by ghost — COMMENTED** [review]
looks good.

**Comment by ghost** [comment]
[[User] - Loading and Error feedback](https://trello.com/c/wUF6YDOU/36-user-loading-and-error-feedback)

**Review by ghost — COMMENTED** [review]
fabulous

**Review by wSedlacek — APPROVED** [review]
Looks good. Good job.

**Comment by wSedlacek** [comment]
Tested Staging:
https://5e222943b4899600087c1de7--story-squad.netlify.com

**Pull request merged**
