### PR TITLE
Scaffold React Application

### PR DESCRIPTION
**Pull request by wSedlacek**
# Description

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by wSedlacek** [comment]
[[Developer] - Setup repository file structure and extension config](https://trello.com/c/ZTpVL88l/25-developer-setup-repository-file-structure-and-extension-config)

**Comment by EricBanker12** [comment]
I found no issues, We may want to add scss as a dependency.

**Review by EricBanker12 — APPROVED** [review]
I found no issues, but we may want to add scss as a dependency.

**Review by ghost — COMMENTED** [review]
This is amazing and neat work. I learnt so much.

**Review by Forrestdarabian — APPROVED** [review]
Very well put together, code is clean, boilerplate setup is great, could use more comments explaining what is doing what, but overall amazing job.

**Comment by wSedlacek** [comment]
> I found no issues, but we may want to add scss as a dependency.

Added SCSS

**Comment by wSedlacek** [comment]
> Very well put together, code is clean, boilerplate setup is great, could use more comments explaining what is doing what, but overall amazing job.

Is there a particular spot(s) you found confusing?

**Pull request merged**
