### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by BNMoyers**
# Description

As a developer, I would like to have accurate and thorough documentation, so that other developers understand and can run/continue our work.

[Trello Card](https://trello.com/c/CXHZWtj1/26-developer-documentation)

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Change Status

- [x] Complete, does not need test, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by EricBanker12** [comment]
[[developer] - documentation](https://trello.com/c/CXHZWtj1/26-developer-documentation)

**Review by ghost — COMMENTED** [review]
updated contributers

**Review by ghost — COMMENTED** [review]
Fe documentation completion

**Review by ghost — COMMENTED** [review]
All commits work beautifully to a complete documentation.

**Review by wSedlacek — APPROVED** [review]
Updated documentation to reflect current status

**Pull request merged**
