### PR TITLE
Stripe elements

### PR DESCRIPTION
**Pull request by BNMoyers**
# Description
   Stripe integration with dashboard and the changes corresponding to the dashboard.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [X] Testing Component Rendering

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
start of strip front end

**Review by ghost — COMMENTED** [review]
rebasing of code.

**Review by ghost — COMMENTED** [review]
checkout page created.

**Review by ghost — COMMENTED** [review]
stripe input form component and check out form component.

**Review by ghost — COMMENTED** [review]
staging of backend.

**Comment by wSedlacek** [comment]
[[Parent] - Manage my children's account and preferences](https://trello.com/c/gLrPV5Wd/21-parent-manage-my-childrens-account-and-preferences)

**Comment by wSedlacek** [comment]
[[Parent] - Use a recognizable payment platform](https://trello.com/c/aOq56W7Y/23-parent-use-a-recognizable-payment-platform)

**Review by EricBanker12 — APPROVED** [review]
All tests pass, and I found everything working during manual testing. However, the parent can still add a child without payment, which may need to be addresses.

The refactoring to other components unrelated to stripe implementation should have been done in a separate feature branch.

**Pull request merged**
