### PR TITLE
Admin Management (Front End)

### PR DESCRIPTION
**Pull request by EricBanker12**
# Description

As an Admin, I would like to upload PDFs, so that users have stories to read

[Trello Card](https://trello.com/c/W71Tol6B/37-admin-upload-pdfs)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Page and Component render tests

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by EricBanker12** [comment]
[[Admin] - Upload PDFs](https://trello.com/c/W71Tol6B/37-admin-upload-pdfs)

**Review by ghost — COMMENTED** [review]
looks great.

**Review by ghost — COMMENTED** [review]
end product video is fabulous! great work.

**Review by wSedlacek — APPROVED** [review]
There is some areas that could be fine tuned but this overall is good work

**Review by wSedlacek — APPROVED** [review]

**Comment by wSedlacek** [comment]
Staging Tested

**Pull request merged**
