### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by ghost**
# Description

As a code reviewer, I would like to see clean code and no unnecessary code, so that it looks polished.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ghost** [comment]
[[Developer] - Polish Application](https://trello.com/c/yEinNJLV/45-developer-polish-application)

**Review by ghost — COMMENTED** [review]
code reviewed.

**Review by ghost — COMMENTED** [review]
Fantastic changes.Looks awesome!!

**Review by EricBanker12 — APPROVED** [review]
All tests pass and manual testing seemed to work fine.

**Pull request merged**
