### PR TITLE
Customize Preferences for my Child

### PR DESCRIPTION
**Pull request by wSedlacek**
# Description
As a Parent, I would like to set my child's accessibility settings, so that my child can participate without struggling

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Rendering test

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by wSedlacek** [comment]
[[Parent] - Customize Preferences for my Child](https://trello.com/c/nVnDmDO9/35-parent-customize-preferences-for-my-child)

**Review by ghost — COMMENTED** [review]
great changes.

**Review by ghost — COMMENTED** [review]
rebasing of code.

**Review by EricBanker12 — COMMENTED** [review]
It looks great so far. All tests passed and manual usage works, but the dyslexia preference can only be accessed through the side bar after creation. There's no edit button on the child's card nor can it be set during child creation.

**Review by EricBanker12 — APPROVED** [review]
See previous comment for details. The UX changes can be a separate feature branch.

**Pull request merged**
