### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by Forrestdarabian**
# Description

Updates Testing to be more functional and running properly
Ensures components and pages render without errors

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
working tests.

**Comment by wSedlacek** [comment]
[Set up test suite](https://trello.com/c/hCp36jtN/7-set-up-test-suite)

**Review by wSedlacek — APPROVED** [review]

**Review by EricBanker12 — APPROVED** [review]
All tests passed locally

**Review by wSedlacek — APPROVED** [review]

**Review by wSedlacek — APPROVED** [review]
Tested test, confirmed passing

**Pull request merged**
