### PR TITLE
changes unregister to register for PWA

### PR DESCRIPTION
**Pull request by ghost**
# Description

As a user, I would like to install story squad on my mobile, so that it acts as progressive web app.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ghost** [comment]
[[User] - Install the app on my device](https://trello.com/c/81ZAFwn0/44-user-install-the-app-on-my-device)

**Comment by ghost** [comment]
[[User] - Install the app on my device](https://trello.com/c/81ZAFwn0/44-user-install-the-app-on-my-device)

**Comment by ghost** [comment]
[[User] - Install the app on my device](https://trello.com/c/81ZAFwn0/44-user-install-the-app-on-my-device)

**Review by wSedlacek — APPROVED** [review]
Looks Good

**Pull request merged**
